apiVersion: v1
kind: PersistentVolume
metadata:
  name: cip-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/cip"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cip-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
