"""create_normalized_schema

Revision ID: 20d1ee6c8d98
Revises: None
Create Date: 2026-07-27 12:22:28.746754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d1ee6c8d98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monthly_charges', sa.Float(), nullable=False),
    sa.Column('total_charges', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('paperless_billing', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_type'), 'contracts', ['contract_type'], unique=False)
    op.create_index(op.f('ix_contracts_payment_method'), 'contracts', ['payment_method'], unique=False)
    op.create_table('importhistories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_service', sa.String(length=10), nullable=False),
    sa.Column('multiple_lines', sa.String(length=50), nullable=False),
    sa.Column('internet_service', sa.String(length=50), nullable=False),
    sa.Column('online_security', sa.String(length=50), nullable=False),
    sa.Column('online_backup', sa.String(length=50), nullable=False),
    sa.Column('device_protection', sa.String(length=50), nullable=False),
    sa.Column('tech_support', sa.String(length=50), nullable=False),
    sa.Column('streaming_tv', sa.String(length=50), nullable=False),
    sa.Column('streaming_movies', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('senior_citizen', sa.Integer(), nullable=False),
    sa.Column('partner', sa.String(length=10), nullable=False),
    sa.Column('dependents', sa.String(length=10), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('churn', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_churn'), 'customers', ['churn'], unique=False)
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customers_tenure_months'), 'customers', ['tenure_months'], unique=False)
    op.create_table('ltv_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('predicted_ltv', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ltv_predictions_customer_id'), 'ltv_predictions', ['customer_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('churn_probability', sa.Float(), nullable=False),
    sa.Column('is_churn', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_customer_id'), 'predictions', ['customer_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('strategy', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_customer_id'), 'recommendations', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_customer_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_predictions_customer_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_ltv_predictions_customer_id'), table_name='ltv_predictions')
    op.drop_table('ltv_predictions')
    op.drop_index(op.f('ix_customers_tenure_months'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_churn'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('services')
    op.drop_table('importhistories')
    op.drop_index(op.f('ix_contracts_payment_method'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_type'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('billings')
    # ### end Alembic commands ###
